<div class="sejarah-gpib">
    <p>Tanggal dan tahun terbentuknya Jemaat GPIB “Marga Mulya” Yogyakarta secara pasti belum diketahui, karena penelitian untuk itu belum dilakukan. Berdasarkan catatan yang diketemukan, pada tanggal 14 Desember 1830 dilaksanakan rapat Majelis Gereja yang pertama. Jemaat gereja pada saat itu masih dilayani oleh seorang Pendeta dari Solo. Karena pada saat itu jemaat belum memiliki gedung gereja, maka kebaktian diselenggara-kan di rumah-rumah anggota jemaat.
    Mulai 8 April 1831, dicoba untuk mengusahakan memperoleh sebuah gedung gereja. Tempat ibadah yang direncanakan adalah gedung sekolah milik pemerintah yang kemudian mendapat persetujuan pemerintah. Gedung sekolah yang dipakai sebagai tempat ibadah warga jemaat tersebut sebelum dan selama dipakai mengalami perbaikan sebanyak 3 kali dengan biaya swadaya warga jemaat. Pada akhirnya dirasakan bahwa gedung sekolah tidak dapat menampung warga jemaat yang jumlahnya semakin bertambah dan disadari perlunya membangun sebuah gereja.</p>
    <p>Sejak 24 Januari 1857, kebaktian-kebaktian gereja tidak lagi diselenggarakan di gedung sekolah akan tetapi diselenggarakan di Balai Karesidenan. Pada waktu itu jemaat telah memiliki Pendeta yaitu Ds. Begemen sebagai Pendeta pertama yang didatangkan ke Yogyakarta. Pada saat itu pembangunan gedung gereja telah dimulai dan ditangani serius. Gambar dan bangunan di buat oleh Ir. P.A van Holm. Berdasarkan catatan rapat Majelis Jemaat pada tanggal 24 Juli 1857 disebutkan bahwa pembangunan gedung gereja sudah berjalan dengan baik meskipun belum selesai seluruh-nya dan masih diperlukan biaya untuk penyelesaian pembangunan gedung gereja dan pengadaan peralatan atau perabot gereja.  Untuk kebutuhan tersebut pendeta pendeta memutuskan mencari dana warga jemaat dan pinjaman dari Dana Diakonia. Pemerintah juga telah ikut membantu pembangunan gedung gereja. Hal ini terbukti dari adanya surat dari pihak gereja tertanggal 29 Mei 1857 yang meminta bantuan pemerintah dan berhasil. Dari Dana Diakonia mendapat pinjaman uanh sejumlah f 700.  Dari catatan yang ada diperoleh keterangan bahwa gedung gereja sungguh-sungguh dibangun atas biaya swadaya anggota jemaat. Hal itu terbukti dari laporan opster G.R Lavalette untuk memberikan perhitungan dan pertanggung-jawaban dari dana-dana yang telah diterima lengkap dengan daftar sumbangan yang telah dipakai habis untuk pembiayaan pembangunan gedung gereja.</p>
    <p>Akhirnya rapat Majelis Gereja tanggal 13 Oktober 1857 menyatakan bahwa pembangunan Gereja telah selesai, pemakaiannya akan dimulai dengan suatu upacara pada tanggal 15 Oktober 1857.
    Dari catatan yang ada disebutkan Sri Sultan tercatat sebagai pribadi yang telah memberikan bantuan secara financial. Uluran tangan Sri Sultan dan Kakandanya Almarhum berupa bahan-bahan bangunan. Untuk itu Majelis Gereja telah menyampaikan ucapan terima kasih.  Seluruh anggaran yang tersedia untuk pembangunan gedung gereja tersebut berjumlah f 16.000, berasal dari sumbangan sukarela sebanyak f 11.000 ditambah Dana Diakonia f 400.  Jumlah tersebut belum termasuk sumbangan berupa bahan-bahan bangunan yang diberikan oleh Sri Sultan dan kakandanya almarhum. Dalam arsip disebutkan gereja memiliki 500 buah kursi.</p>
    <p>Belum ada sepuluh tahun sejak berdirinya, tepatnya tahun 1862 gedung gereja mengalami kerusakan karena dilanda gempa bumi sehingga kebaktian-kebaktian kembali diselenggarakan di gedung sekolah. Karena kebaktian masih dijalankan sampai Desember 1868 maka disimpulkan bahwa kerusakan gedung cukup parah, sehingga keuangan yang ada tidak cukup bagi perbaikan  gedung gereja. Akan tetapi pada bulan November 1868, Majelis Gereja dengan perantaraan Asisten Residen menerima bantuan keuangan sehubungan dengan kerugian karena gempa bumi sejumlah uang f 5000, akan tetapi tidak dijelaskan siapa yang memberikan sejumlah bantuan tersebut. Biaya perbaikan menghabiskan dana f 3867,25. Sejak saat itu gedung Gereja tidak banyak disebutkan lagi dalam arsip. Yang jelas bahwa gedung Gereja itulah yang masih berdiri sampai saat ini dan tepat 15 Oktober 2000 telah berusia 143 tahun.</p>
    <p>Dalam perkembangannya, kapasitas gedung gereja dirasakan sudah tidak mampu menampung jemaat yang makin bertambah. Karena kesulitan dana baru pada tahun 1985 diputuskan dalam rapat Majelis Gereja untuk dilakukan rehabilitasi gedung gereja. Dalam keputusan Majelis Gereja menyebutkan bahwa perlu dilakukan perluasan berupa perkantoran (konsistori) dan ruang ibadah (balkon). Untuk melaksanakan tugas tersebut dibentuklah Panitia Rehabilitasi Gereja yang bekerja berdasarkan Surat Keputusan Majelis Sinode GPIB No. 1896/86/MS/XIII/Kpts tertanggal 19 Juli 1986. Panitia Rehabilitasi tersebut diketuai oleh Supangat, BSc.   Dengan menggunakan pemborong CV. Pembina. Panitia telah berhasil menyelesaikan balkon sehingga daya tampung gedung bertamba 100 kursi.  Untuk penyelesaian rehabilitasi gereja maka SK Panitia diperpanjang dengan SK Majelis Sinode GPIB Nomor: 1896/96/MS/XIII/Kpts tanggal 21 Januari 1987.</p>
    <p>Untuk tahap ini tanpa menggunakan pemborong, panitia berhasil membangun ruang konsistori bertingkat di dalam gedung gereja, 2 kamar mandi/wc, ruang persiapan/perlengkapan, serta pemugaran keliling gedung gereja, pembuatan saluran limbah air, perbaikan ruang parkir dan perbaikan atas gedung gereja.
    Dengan diresmikannya semua yang telah berhasil dicapai dalam usaha rehabilitasi ini, bukan berarti bahwa rehabilitasi gedung gereja telah selesai seluruhnya. Rehabilitasi ini masih akan dilanjutkan. Biaya rehabilitasi gedung gereja selama ini sebesar Rp. 25.000.000,- bersumber dari keuangan jemaat, dan pemerintah Daerah Istimewa Yogyakarta sebesar Rp. 400.000,-   Dalam suatu catatan sejarah yang tidak dilupakan bahwa tanggal 24 Desember 1947 Ir. Soekarno Presiden pertama Indponesia beserta Ibu Fatmawati  mengikuti perayaan Natal disertai oleh Jenderal Purbonegoro dan memberikan sambutannya.</p>
</div>
