<div class="sejarah-gpib">
    <p>Sejarah GPIB tidak dapat dipisahkan dari pembentukan De Protestantse Kerk In Nederlands Indie pada tahun 1605 di Ambon Maluku, Hindia Belanda. Namun di tahun 1619, kantor pusat De Protestantse Kerk In Nederlands Indie dipindahkan ke Batavia sehubungan dengan berpindahnya kedudukan Gubernur Jenderal Hindia Belanda dari Ambon ke Batavia.</p>
    <p>De Protestantse Kerk In Nederlands Indie, mewarisi jemaat-jemaat yang ditinggalkan oleh Portugis dengan wilayah pelayanannya meliputi sejumlah daerah seperti Maluku, Minahasa, Kepulauan Sunda Kecil (kini Nusa Tenggara Timur, dan sebagian Nusa Tenggara Barat khususnya Pulau Sumbawa dan sebagian Lombok), serta Pulau Jawa, Sumatera dan lainnya.</p>
    <p>Karena wilayah pelayanan semakin banyak dan meluas, maka cabang-cabang De Protestantse Kerk In Nederlands Indie mengalami berbagai persoalan. Pada tahun 1927 disepakati bahwa keesaan gereja harus tetap dipertahankan, namun wilayah yang memiliki kekhususan diberi status mandiri yang lebih luas untuk mengatur pelayanannya secara sendiri-sendiri.</p>
    <p>Dalam Sidang Sinode De Protestantse Kerk In Nederlands Indie tahun 1933, jemaat di Minahasa, Maluku, bekas wilayah Keresidenan Timor dan pulau-pulau di sekitarnya diberikan wewenang untuk menjadi gereja mandiri dalam persekutuan De Protestantse Kerk In Nederlands Indie. Pada tahun 1934, jemaat di Minahasa dilembagakan menjadi gereja mandiri pertama dengan nama Gereja Masehi Injili di Minahasa (GMIM). Setahun kemudian pada tahun 1935, jemaat di Maluku dilembagakan menjadi gereja mandiri kedua dengan nama Gereja Protestan Maluku (GPM). Setelah berakhirnya Perang Dunia II, pada tahun 1947, jemaat di wilayah Sunda Kecil dilembagakan menjadi gereja mandiri ketiga dengan nama Gereja Masehi Injili di Timor (GMIT).</p>
    <p>Sidang Sinode De Protestantse Kerk In Nederlands Indie yang diadakan di Buitenzorg (Bogor), menyepakati bahwa gereja mandiri keempat akan dibentuk dengan wilayah pelayanan di bagian barat Indonesia. Pada tanggal 31 Oktober 1948, dalam Ibadah Minggu Jemaat di "Willems Kerk" (sekarang Gereja Immanuel Jakarta), dilembagakanlah gereja mandiri keempat yang pada waktu itu bernama De Protestantse Kerk in Westelijk Indonesie (Gereja Protestan di Indonesia bagian Barat), berdasarkan Tata Gereja dan Peraturan Gereja yang dipersembahkan oleh proto-Sinode kepada Algemene Moderamen De Protestantse Kerk In Nederlands Indie (Badan Pekerja Am Gereja Protestan di Indonesia).</p>
</div>

<div class="mt-5">
    <small class="font-italic">Sumber: <a href="http://gpib.or.id">www.gpib.or.id</a></small>
</div>
